name: Build Next.js web application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Insatall NPM dependencies
        run: npm install

      - name: Build project assets
        run: npm run build
